### ISSUE TITLE
Roadmap for OpenRL

### ISSUE THREAD

**Issue by huangshiyu13** [OpenRL-Lab/openrl#2]
This issue will keep tracking of OpenRL's updates of the subsequent few versions:

**v1.0.0**
- [ ] support multi-machine/node training

**v0.2.1** (in progress)
- [x] #296 
- [ ] #15 

**v0.2.0**
- [x] #19 #282
- [x] #268 
- [x] #272  
- [x] #276  
- [x] #278  

**0.1.9**
- [x] #258 
- [x] #256 
- [x] #262  

**0.1.8** 
- [x] #244 
- [x] #249 
- [x] #250  
- [x] #253  

**0.1.7** 
- [x] #235 
- [x] #240  

**0.1.6** 
- [x] #230 

**0.1.5** 
- [x] #224 
- [x] #225  
- [x] #226  
- [x] #227 

**0.1.4** 
- [x] #217 
- [x] #218 
- [x] #218  

**0.1.3**
- [x] #212 

**0.1.2** 
- [x] #201 
- [x] #209  

**0.1.1** 
- [x] #187 
- [x] #189 
- [x] #190  
- [x] #193 
- [x] #194  

**0.1.0**
- [x] #177 
- [x] #182 

**0.0.15**
- [x] #169 
- [x] #174 

**0.0.14** 
- [x] #158 
- [x] #161 

**0.0.13**
- [x] #130 
- [x] #122 
- [x] #144  

0.0.12
- [x] #108 
- [x] #106 
- [x] #103  
- [x] #109 
- [x] #114  
- [x] #115  
- [x] #117 

**0.0.11**
- [x] #83 
- [x] #88 

**0.0.10**
- [x] #67 #73 
- [x] #71  #74 
- [x] #77  
- [x] #78  

**0.0.9**
- [x] #55 
- [x] #60 
- [x] #59 
- [x] #58 
- [x] #57 

**0.0.8**
- [x] improve code testing coverage
- [x] #40 
- [x] #41  
- [x] fix minor bugs 

**0.0.7** 
- [x] #27 
- [x] #29  

**v0.0.6** 
- [x] import hugging face models/datasets
- [x] dictionary observation support
- [x] multi-agent training support
- [x] dialog training support
- [x] fix existing bugs
- [x] add more examples
- [x] optimize Contributing docs
- [x] fix existing errors in openrl-docs

**Comment by GodRishUniverse** [comment]
Is this still in development?
